export interface IData {
    id: string | number | null,
    registerNo: string | null,
    frameNumber: string | null,
    machineNumber: string | null,
    manufacturer: string | null,
    vehicleTypeId: string | number | null,
    capacity: number | null,
    image: any | null,
    intendedUse: number | null,
    routeId: string | number | null,
    odometer: number | null,
    firstStartDate: string | null,
    subscriptionDate: string | null,
    registrationDate: string | null,
    registrationExpireDate: string | null,
    tndsInsuranceStartDate: string | null,
    tndsInsuranceEndDate: string | null,
    materialInsuranceStartDate: string | null,
    materialInsuranceEndDate: string | null,
    badgeIssuanceStartDate: string | null,
    badgeIssuanceEndDate: string | null,
    travelPermitStartDate: string | null,
    travelPermitEndDate: string | null,
    roadMaintenanceFee: any | null,
    feePaymentDate: string | null,
    feeExpireDate: string | null,
    cellphonePlan: string | null,
    networkProvider: string | null,
    networkRegisterDate: string | null,
    networkExpireDate: string | null,
    gpsDevice: string | null,
    gpsDeviceSetupDate: any | null,
    status: number | null,
    createdBy: string | null,
    createdDate: string | null,
    lastModifiedBy: string | null,
    lastModifiedDate: string | null,
}